version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_management
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql

  customers-api:
    build:
      context: ./customers-api
    container_name: customers-api
    restart: always
    environment:
      PORT: 3001
      DB_HOST: mysql        # 👈 se conecta por el nombre del servicio
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_NAME: order_management
      JWT_SECRET: supersecret
    ports:
      - "3001:3001"
    depends_on:
      - mysql