openapi: 3.0.3
info:
  title: Customers API
  version: 1.0.0
  description: API para gestionar clientes
servers:
  - url: http://localhost:3001
paths:
  /customers:
    get:
      summary: Buscar clientes
      parameters:
        - in: query
          name: search
          schema:
            type: string
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        "200":
          description: Lista de clientes
    post:
      summary: Crear un cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerInput"
      responses:
        "201":
          description: Cliente creado
  /customers/{id}:
    get:
      summary: Obtener cliente por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Cliente encontrado
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        phone:
          type: string
    CustomerInput:
      type: object
      required: [name, email, phone]
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
